### ISSUE TITLE
game crashes when trying to expand 'save states' tab while searching for ranked match

### ISSUE THREAD

**Issue by noittaM** [libreofficecalc/BBCF-Improvement-Mod#35]
if you enter ranked search and go to training room, attempting to to expand the 'save states' tab crashes the game.
this isn't the case with other tabs and seems to only happen when in ranked search.

**Comment by libreofficecalc** [comment]
The crash happens here: https://github.com/libreofficecalc/BBCF-Improvement-Mod/blob/ecadf7da42c2f6659cef895ba6bdbc4967092c96/src/Game/SnapshotApparatus/SnapshotApparatus.cpp#L61

This is because the initialization of the statics for rollback access for some reason crashes when the ranked search is enabled, probably because some manner of initialization is done already to allow for the search to happen.  

I must investigate further to fix it.

**Comment by libreofficecalc** [comment]
closing it as not planned for now, given how a safeguard for it was added and currently on time restraints
